### PR TITLE
move node-xmpp-server here

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by sonnyp** [comment]
cc @hyperlink for your information

**Comment by sonnyp** [comment]
once merged

```
git clone git@github.com:node-xmpp/node-xmpp.git
npm install
npm run bootstrap
npm test
```

server code is in node-xmpp/packages/node-xmpp-server

**Comment by sonnyp** [comment]
@hyperlink done :)

**Comment by hyperlink** [comment]
@sonnyp what's the plan for the old `server` repo and module? Will it still be maintained for awhile?

**Comment by sonnyp** [comment]
I'm leaving it open for now but no new issue/PR/code should be submitted

**Comment by sonnyp** [comment]
use https://github.com/node-xmpp/node-xmpp instead

**Comment by hyperlink** [comment]
If I understand correctly the [server](https://www.npmjs.com/package/node-xmpp-server) module will still be on npm the only difference is we will be publishing from this repo. Specifically from  `/packages/node-xmpp-server`?

**Comment by sonnyp** [comment]
exactly, sorry it wasn't clear

**Pull request merged**
