### PR TITLE
use upstream pem module

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by sonnyp** [comment]
review? @dexus

**Comment by Dexus** [comment]
Look's correct. But i don't understand why it fails. Timeout is not from PEM module.

**Comment by sonnyp** [comment]
no, it's something else on Node.js 0.10 and 0.12 probably a race condition, merging and will have a look

**Comment by sonnyp** [comment]
@Dexus thanks again

**Comment by Dexus** [comment]
no problem, you're welcome

**Pull request merged**
