### PR TITLE
fixed windows commands using compat

### PR DESCRIPTION
**Pull request by mavericken**

### CODE REVIEW

**Comment by sonnyp** [comment]
@mavericken thanks; why not using one of the numerous tool to get a unix-y env on Windows?

**Comment by mavericken** [comment]
@sonnyp Do you have a suggestion?  My experience has been wastelandish.

**Comment by sonnyp** [comment]
@mavericken https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by mavericken** [comment]
@sonnyp Ah yeah, I did see that.  I didn't try it though because I read stuff about how it doesn't actually interop with windows, and still runs a VM.  Its alright though, putting in the work to making stuff "just work" is worth it, as it is kinda why node.js appealed to me in the first place.

By the way, is there a way to get travis-ci to just... try again?  I feel like it failed because of unrelated timing issues or something.

**Comment by sonnyp** [comment]
@mavericken WSL is not a VM. I recommend you try it; it's neat.

I'm not very in favor of supporting Windows for node-xmpp development because I don't have much much time to dedicate to it and I'm not interested of supporting that.

**Comment by mavericken** [comment]
@sonnyp So I tried it, but it didn't pass my sniff test.  I get various errors and nothing really works right, not worth messing with in its current state in my opinion.

**Comment by sonnyp** [comment]
@mavericken good to hear

**Comment by mavericken** [comment]
Update:  Experience is still wastelandish.  WSL is simply not ready yet.  Wasted a bunch of time on it.

**Pull request closed without merging**
