### PR TITLE
Conform to the new plugin API

### PR DESCRIPTION
**Pull request by ggozad**

### CODE REVIEW

**Comment by sonnyp** [comment]
@ggozad any feedback on the API? do you like it?

**Comment by ggozad** [comment]
So far it looks great! I am hoping to get some time today to start on the pubsub which also includes handlers and what not. So my guess is more feedback on the way, but it looks good. MIght be worth looking into a classs MyPlugin extends Plugin type of thing for clarity....

**Comment by sonnyp** [comment]
Cool.

> MIght be worth looking into a classs MyPlugin extends Plugin type of thing for clarity....

Sorry I don't follow.

**Comment by ggozad** [comment]
Never mind, I just looked at plugin.js and it does exactly what I was going to propose :)
A question: I would like to be able to develop our product on the same time and keep our own plugins current. It's also easier to test certain integration thingies with a real server.
I can add @xmpp/client  
yarn add file://Users/ggozad/dev/open-source/node-xmpp/packages/client
but fail on the plugins (complains about not finding @xmpp/events even if I install it locally.  How would you go around that?

**Comment by sonnyp** [comment]
https://yarnpkg.com/lang/en/docs/cli/link/

**Comment by ggozad** [comment]
Ops of course, thanks, very new to node :)

**Comment by ggozad** [comment]
Bah, the react native packages fucks up with symlinks... :(

**Comment by sonnyp** [comment]
@ggozad :(

Maybe clone/make directly into your node_modules/ folder and `require('./node_modules/node-xmpp/packages/client')` for now ?

**Comment by ggozad** [comment]
Yep, that's what I ended up doing.... Sorry to bother you with all that :)

**Pull request merged**
